# Generated by Django 4.0.2 on 2022-02-02 16:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestTask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
